### ISSUE TITLE
April Release Checklist

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-app-rdm#107]
Our goals for the April release are:

Please feel comfortable ticking them off and adding the tasks that are missing  :smiley: .

**Deposit Backend**
- [x] To have settled the big lines of the Deposit API: 
  - [x] Controller RFC: https://github.com/inveniosoftware/rfcs/issues/23 Cleaned up.
  - [x] Deposit Rest API RFC: https://github.com/inveniosoftware/rfcs/issues/22 Cleaned up.
- [x] proof of concept for deposit API
  - [x] Generate empty initial record for frontend https://github.com/inveniosoftware/invenio-rdm-records/pull/91 (See blockers below)
  - [x] Generate controlled vocabulary(ies) for frontend https://github.com/inveniosoftware/invenio-rdm-records/pull/91 (See blockers below)
- [x] branch for flask-resources: https://github.com/inveniosoftware/flask-resources/pull/1
- [x] branch for invenio-resources: https://github.com/inveniosoftware/invenio-resources/pull/1
  - [x] Remove: invenio-resources-bk from ppanero personal GitHub https://github.com/ppanero/invenio-resources-bk
  - [x] Remove: flask-resources from lnielsen personal GitHub https://github.com/lnielsen/flask-resources
  - [x] Remove: local copies of said repos
- [x] Create resources development branch with working integration in:
  - [x] invenio-app-rdm (https://github.com/inveniosoftware/invenio-app-rdm/tree/resources)
  - [x] invenio-rdm-records (https://github.com/inveniosoftware/invenio-rdm-records/tree/resources)

**Deposit Frontend**
- [x] To have settled on the big lines of the Deposit frontend: https://github.com/inveniosoftware/rfcs/issues/27 (Codimd: https://codimd.web.cern.ch/_l39jjcmQX2Q40jpCDu6GQ#). Cleaned up.
- [x] Proof of concept for deposit page: fill 2 fields 
  - [x] button with action (Save Draft + Publish buttons with faked actions)
  - [x] field (titles, resource type)
    - [x] titles
    - [x] resource type
  - [x] loads passed config
  - [x] loads empty initial record
  - [x] loads pre-existing record (record is still fake) Needs to merge existing record with empty one so the user can fill in the missing parts
  - [x] shows error message
  - [x] URL re-write
  - [x] Backend error handling in frontend end (ErrorHandler class, faked api response errors)
  - [x] Transformation layer (on receiving a record, before submitting a record)
  - [x] Confirm Modal before publishing
- [x] Merge invenio-app-rdm/deposit branch into master and release

**CLI + Cookiecutter**
- [x] Release updated cookiecutter + updated cli using it

**Blockers**
- [x] Missing email-validator library due to latest 2.3.1 WTForms is breaking Travis everywhere. Quick fix here: https://github.com/inveniosoftware/invenio-accounts/pull/312 (needs to be merged)

**S3**
- [x] Improvements to big file uploads (egabancho 's contribution): https://github.com/inveniosoftware/invenio-s3/issues/11
  * v1.0.3 has been released with improvements on big files uploads. Should be transparent since is compatible with v1.0.2 currently pinned.

**Invenio-Indexer**
- [x] inveniosoftware/invenio-indexer#118. PR for supporting a custom record class for indexing. Needed in invenio-communities.

**Cookiecutter-RDM**

- [x] Slugify project name: https://github.com/inveniosoftware/cookiecutter-invenio-rdm/issues/45
- [x] Unpin WTForms: https://github.com/inveniosoftware/cookiecutter-invenio-rdm/issues/67

**Developer Experience**

- [x] inveniosoftware/pywebpack#23 Implement symlinks on folder level (expects 2 level folder e.g js/invenio_app_rdm -> symlinks invenio_app_rdm). Plays well with the folder convention assets/js/<module_name>
- [x] inveniosoftware/invenio-assets#108. Integrates folder symlinks, source maps in development, patches out of the box watchpack/DirectoryWatcher, enables LinkStorage in development mode.

@ppanero @zzacharo @lnielsen

**Comment by fenekku** [comment]
April release done: https://invenio-talk.web.cern.ch/t/inveniordm-alpha-6-april-release/104

Closing this.
