### ISSUE TITLE
[EPIC] semantic-ui integration with invenio v3.4.0a1

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-app-rdm#124]
**Documentation:**

- RFCs (*what is this madness?*) 
    - [Templating/assets building: Multi theme support](https://codimd.web.cern.ch/pUeMi9SoQpyhuTG01JkERg)
    - [React-Searchkit integration: Overridable customization](https://codimd.web.cern.ch/338rA780SRahrk1HyhPkGw)
- Getting started
   - [Module migration guide](https://codimd.web.cern.ch/bfDyh_ejQJSq-DZpGCSfMA) 
   - [Developer quickstart](https://codimd.web.cern.ch/BSUwGIS4Q9OtbVAqVn7e7w)

**Steps:**

- [x] 1. Update `cookiecutter-invenio-rdm` to support Python 3.7 and 3.8. https://github.com/inveniosoftware/cookiecutter-invenio-rdm/issues/71
   - [x] Quick win: fix https://github.com/inveniosoftware/cookiecutter-invenio-rdm/issues/64 as part of the work.
- [x] 2. Integrate Invenio v3.4.0a1. Set `APP_THEME=['bootstrap3']`. InvenioRDM should stay as is now, no UI should be broken. https://github.com/inveniosoftware/cookiecutter-invenio-rdm/issues/72
    - [x] Update dependencies in `invenio-rdm-records: https://github.com/inveniosoftware/invenio-rdm-records/issues/102
    - [x] Update dependencies in `invenio-records-permissions`: https://github.com/inveniosoftware/invenio-records-permissions/issues/47
    - [x] Using an alpha release will incur in using `--pre` in `invenio-cli`. Crosscheck how this affect 3rd party dependencies. *Is there any dependency breaking code?* --> NO
-  [x] 3. Release modules:
   - [x] Release rdm-records: https://github.com/inveniosoftware/invenio-rdm-records/issues/108
   - [x] Release records-permissions: https://github.com/inveniosoftware/invenio-records-permissions/issues/49
-  [x] 4. Migrate to Semantic-UI. Set `APP_THEME=['semantic-ui']`.
   - [x] Migrate templates in `invenio-app-rdm`. https://github.com/inveniosoftware/invenio-app-rdm/issues/125
   - [x] Migrate templates in `invenio-rdm-records`. https://github.com/inveniosoftware/invenio-rdm-records/issues/100
   - [x] Update `cookiecutter-invenio-rdm` to build the new UI bundles. See https://github.com/inveniosoftware/cookiecutter-invenio-instance/pull/227 for reference.
-  [x] 5. Release modules:
   - [x] Release rdm-records: https://github.com/inveniosoftware/invenio-rdm-records/issues/108
   - [x] Release app-rdm

**Comment by ppanero** [comment]
All steps have been implemented. Closing issue.

Next step theming https://github.com/inveniosoftware/cookiecutter-invenio-rdm/issues/75
