### ISSUE TITLE
[EPIC] June Release Checklist

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-app-rdm#202]
- [x] Finish Semantic UI migration.
    - [x] Fix invenio-previewer
      - [x] Release invenio-previewer
      - [x] Bump previewer and release Invenio `v3.4.0a6`
    - [x] Release invenio-account (https://github.com/inveniosoftware/invenio-accounts/issues/337)
    - [x] Release invenio-userprofiles (https://github.com/inveniosoftware/invenio-userprofiles/issues/108)
    - [x] Release invenio-theme (https://github.com/inveniosoftware/invenio-theme/issues/189)
    - [x] Invenio-OAuthClient (https://github.com/inveniosoftware/invenio-oauthclient/issues/213)
        - ~~[] Does https://github.com/inveniosoftware/invenio-oauthclient/pull/211 go in?~~ NO
    - [x] Release Invenio-OAuth2Server (https://github.com/inveniosoftware/invenio-oauth2server/issues/210)
         - [x] Does https://github.com/inveniosoftware/invenio-oauth2server/pull/211 go in?
         - [x] If above is *yes* --> Release 1.3.0a2 and bump below
    - [x] Release Invenio 3.4.0a5 with the new modules: 
        - invenio-theme 1.3.0a10
        - invenio-accounts 1.4.0a5
        - invenio-userprofiles 1.2.0a3
        - invenio-oauth2server 1.3.0a2
        - invenio-oauthclient 1.4.0a1
- [x] Release invenio-app-rdm. Bump invenio and invenio-rdm-records (https://github.com/inveniosoftware/invenio-app-rdm/issues/204 --> https://github.com/inveniosoftware/invenio-app-rdm/pull/206)
- [x] Make contributors not mandatory https://github.com/inveniosoftware/invenio-rdm-records/pull/126
    - [x] Requires idutils release https://github.com/inveniosoftware/idutils/pull/65
- [x] invenio-rdm-records
    - [x] Need to doublecheck this https://github.com/inveniosoftware/invenio-rdm-records/issues/128
    - ~~[ ] Bump previewer dependency (requires release of it)~~ No need since it has `<2.0.0`
    - [x] Integrate previewer changes https://github.com/inveniosoftware/invenio-rdm-records/pull/130
    - [x] Merge https://github.com/inveniosoftware/invenio-rdm-records/pull/129#issuecomment-650250163
    - [x] Release invenio-rdm-records
- [x] React modules:
    - [x] Review and merge: https://github.com/inveniosoftware/react-invenio-deposit/pull/40
    - [x] Review and merge: https://github.com/inveniosoftware/react-invenio-deposit/pull/44
    - [x] Bump and release react-invenio-deposit  https://github.com/inveniosoftware/react-invenio-deposit/pull/45
- [x] Release invenio-app-rdm.
  - [x] Would be nice to fix https://github.com/inveniosoftware/invenio-app-rdm/issues/195
  - [x] Update dependencies on react-invenio-deposit
  - [x] Update dependencies on invenio-rdm-records 
  - [x] Bump invenio version after previewer
- [x] Update cookiecutter-invenio-rdm with new invenio-app-rdm release.
~~- [ ] Allow JSX templates customization~~
- [x] More on Flask-Resources
    - [x] Remove usage of reserved keywords https://github.com/inveniosoftware/flask-resources/issues/35
    - ~~[ ] Perform authentication (not authorization) https://github.com/inveniosoftware/flask-resources/issues/8~~
    - [x] Fix order in error responses https://github.com/inveniosoftware/flask-resources/issues/36
    - [x] Serialize exceptions
    ~~- [ ] Release Flask-Resources new alpha (blocked: need API key)~~
- [x] Create `0.10.0` branch in cookiecutter-invenio-rdm
- [x] Update default branch in Invenio-CLI
    - [x] Release Invenio-CLI https://github.com/inveniosoftware/invenio-cli/pull/143
- docs-invenio-rdm
  - [x] update with invenio-rdm-records changes (https://github.com/inveniosoftware/invenio-rdm-records/issues/128)
  - [x] Merge https://github.com/inveniosoftware/docs-invenio-rdm/pull/58
  - [x] Merge master to maint
- New backend
- [x] Merge PRs in Flask-Resources
- [x] Merge PRs in Invenio-Resources
- [x] Merge PRs in Invenio-Records-Agent
    - ~~[ ] Create Invenio-Records-Service repository~~
    - ~~[ ] Rename repo and related objects to invenio-records-service~~
- [ ] Write a not on how to install this repositories in case someone wants to use them.

**Running the current development InvenioRDM**

Install:
- Invenio-CLI 0.14.2 --> Invenio-App-RDM 0.9.8 & Invenio 3.4.0.a5
- Flask-Resources from master
- Invenio-Resources from ppanero@dev (https://github.com/ppanero/invenio-records-agent)
