### ISSUE TITLE
Notifications support

### ISSUE THREAD

**Issue by zzacharo** [inveniosoftware/invenio-app-rdm#2065]
```[tasklist]
### Tasks
- [ ] https://github.com/inveniosoftware/cookiecutter-invenio-module/pull/147
- [ ] https://github.com/inveniosoftware/invenio-notifications/issues/1
- [ ] https://github.com/inveniosoftware/invenio-notifications/issues/2
- [ ] https://github.com/inveniosoftware/invenio-records-resources/issues/440
- [ ] https://github.com/inveniosoftware/invenio-records-resources/issues/450
- [ ] https://github.com/inveniosoftware/invenio-notifications/issues/3
- [ ] https://github.com/inveniosoftware/invenio-rdm-records/issues/1179
- [ ] https://github.com/inveniosoftware/invenio-notifications/issues/5
- [ ] https://github.com/inveniosoftware/invenio-app-rdm/issues/2204
- [ ] https://github.com/inveniosoftware/invenio-requests/issues/304
- [ ] https://github.com/inveniosoftware/invenio-communities/issues/889
- [ ] https://github.com/inveniosoftware/invenio-app-rdm/issues/2069
- [ ] https://github.com/inveniosoftware/invenio-communities/issues/864
- [ ] https://github.com/inveniosoftware/invenio-notifications/issues/4
```

New repository at https://github.com/inveniosoftware/invenio-notifications

### Previous RFC

https://codimd.web.cern.ch/RH_steApSGOk4Yaoex782A#notifications

### Issues/comments

- Next steps: https://github.com/inveniosoftware/invenio-requests/issues/271
- Next steps (Alex): https://github.com/inveniosoftware/invenio-requests/pull/257#pullrequestreview-1039435886

### Open PRs

- RFC: https://github.com/inveniosoftware/rfcs/issues/63
- Requests: https://github.com/inveniosoftware/invenio-requests/pull/257
- RDM-Records: https://github.com/inveniosoftware/invenio-rdm-records/pull/990
- Communities: https://github.com/inveniosoftware/invenio-communities/pull/767
- All PRs are rebased on top of current `master`

### Next steps

![Image](https://user-images.githubusercontent.com/1814661/229537687-8d86cc02-77a7-4aba-95b9-0692f53c53c9.png)

- Move `invenio_requests/notifications` to a new `invenio-notifications` module
  - Also merge https://github.com/inveniosoftware/cookiecutter-invenio-module/pull/147 for bootstrapping
- Decouple notifications from events logic (at least for now).
- We want the notifications module to have responsibility for:
  - Defining different backends (email, Slack, push notification, etc.)
    - Each of these should be implemented to allow easy customization of templating/rendering.
  - Common datamodel of what a "client" has to provide when sending notifications (sender, recipients, data/payload, etc.)
  - Mechanics/control of triggering and retrying notification delivery in the backends
- We **don't want** the notifications module to:
  - Be responsible for any business logic, such as:
    - Defining who are the notification recipients or what notification backends should be used
      - This should be decided on the service and the entire user data should be dumped and passed in the notification payload
    - Resolving/enhancing payloads, e.g. by dereferencing entities (users, records, reviews, communities) or generating URLs/links
  - Have knowledge of all the possible events or message types. This should just be an attribute/field as part of the notification datamodel
- Introduce a new `User.preferences.notifications` configuration so that users can easily enable/disable all notifications.
  - We can later add more granular levels of notification settings, e.g. on the global community level or even per community member.
  - Check if it's easy to also add `User.preferences.locale` (to be used in templates); see also [the relevant I18N code](https://github.com/inveniosoftware/invenio-i18n/blob/be68607e702cb34638f6dd07fda3acab365fe644/invenio_i18n/selectors.py#L54)
- Update the [original RFC](https://codimd.web.cern.ch/RH_steApSGOk4Yaoex782A)

### Decisions

- **What is the mechanism for creating notifications?** Some likely candidates:
  - ✅  UoW operation, e.g. `NotificationOp` (we already have `ChangeNotificationOp` for a different use-case)

- **Where is the notification mechanism triggered?**. See examples for clarity:
  - For a review subsmission:
    - `ReviewService.submit()`
    - `SubmitAction.execute()`
  - For creating a comment:
    - `RequestEventService.create()`
  - For accepting/rejecting a request:
    - `AcceptAction.execute()`
  - ✅ Decision: depends on the use-case, we have to evaluate individually

![Image](https://user-images.githubusercontent.com/1814661/217536403-62d75e39-749b-473c-ac34-014d3cad2ada.png)
