### ISSUE TITLE
[EPIC] Search records: GET /records

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-app-rdm#212]
- [x] pagination URL query strings see https://github.com/inveniosoftware/invenio-records-resources/issues/33
- [x] serialization format for search
  * body links
  * pagination
  * header links [optional]
- [x] permissions
  * [x] can_list -> can_search
- [x] Error handling [crosscutting] [errors]
