### ISSUE TITLE
[July Release] Get, search, create and publish via new API

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-app-rdm#215]
This is the mega epic for the July release. It also already holds the release tasks. 

I took the liberty of putting off some of the original items to the next sprint since there is a lot and the next sprint being about just files would accommodate work on other things since we can't all work on files. In any case, we will review this, so feel free to make suggestions.

- [x] [EPIC] Implement GET /records/:id (created by invenio-cli demo) via new API  #213
  - resolve PID
  - implement JSON record serializer [crosscutting]
  - error handling [crosscutting] [errors]
  - check permission [optional]
- [x] [EPIC] Implement the GET /records (Search a record) #212
    - pagination URL query strings [separate]
    - serialization format for search [separate]
      * body links
      * pagination
      * header links [optional]
    - Error handling [crosscutting] [errors]
    - *optional section*
    - Permissions filtering [crosscutting] [optional]
    - Implement a query translator API [optional]
- [x] [EPIC] Implement the POST /records/:id (Create a draft record) via new API #211
  - Deserilization of request data. [crosscutting] https://github.com/inveniosoftware/flask-resources/issues/62
  - Mint a PID (recid)
  - One DB table for records, and one DB table for drafts [data] [internal]
  - Indexing of the draft and record (using one mapping/JSONSchema) [data] [internal]
  - Mapping of service errors to HTTP errors. [crosscutting] [errors] [separate]
  - Data validation with Marshmallow [crosscutting] [errors] [marshmallow] [separate]
  - *optional section*
  - Permission checks and integration of Invenio-Records-Permissions [crosscutting] [optional]
  - Finding a solution for system fields (pids, access control, ...) [optional]
  - Port versioning from Zenodo [optional]
- [x] [EPIC] Implement the POST /records/:id/actions/publish (publish record) via new API #210
- [x] Connect API to frontend in invenio-app-rdm / react-invenio-deposit #209 
  * release react-invenio-deposit if need be
- [x] Map + serialize general Exception to HTTP exceptions #214
- [x] [EPIC] Translate frontpage, Record landing page, deposit page, search page

#### Releases
- [x] Update flask-resources to 0.2.X
- [x] Update invenio-records-resources to 0.3.X
- [x] Update invenio-drafts-resources to 0.1.X
- [x] Update invenio-rdm-records to 0.17.X
- [x] Update invenio-app-rdm 0.11.X
- [x] Update cookiecutter to 0.11.X
- [x] Update invenio-cli to 0.15.X
- [x] Update and release docs

- **Achieved if**: Achieved if with the July release, you can get, search, create and publish a record with the new API (meaning that the hard problems in the new API have all been fixed).

**Comment by fenekku** [comment]
Closing as complete :tada:
