### ISSUE TITLE
[EPIC] Translate App-RDM, Accounts and UserProfiles into Turkish

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-app-rdm#217]
Translate the following modules into Turkish

- [x] App-RDM via https://github.com/inveniosoftware/invenio-app-rdm/pull/216
- [x] Accounts via https://github.com/inveniosoftware/invenio-accounts/pull/340
- [x] UserProfiles via https://github.com/inveniosoftware/invenio-userprofiles/pull/111
- [x] Theme via https://github.com/inveniosoftware/invenio-theme/pull/193

In addition:

- [ ] Document how to install VSCode helper extension.
- [ ] Create list of modules that needs translations
- [ ] Create a task list for I18N (what other tasks should we do - transifex workflow etc).

**Comment by fenekku** [comment]
Marking done! Thanks @baldemir!
