### ISSUE TITLE
github: github integration

### ISSUE THREAD

**Issue by alejandromumo** [inveniosoftware/invenio-app-rdm#2249]
Taken from https://github.com/zenodo/rdm-project/issues/10

```[tasklist]
### Tasks
- [ ] https://github.com/inveniosoftware/invenio-webhooks/issues/65
- [ ] https://github.com/inveniosoftware/invenio-github/issues/98
- [ ] https://github.com/inveniosoftware/invenio-github/pull/117
- [ ] https://github.com/inveniosoftware/invenio-github/issues/102
- [ ] https://github.com/inveniosoftware/invenio-app-rdm/issues/2281
- [ ] https://github.com/inveniosoftware/invenio-github/issues/112
- [ ] https://github.com/zenodo/zenodo-rdm/issues/407
- [ ] https://github.com/inveniosoftware/invenio-github/issues/101
- [ ] https://github.com/inveniosoftware/invenio-github/issues/100
- [ ] https://github.com/inveniosoftware/invenio-github/issues/114
- [ ] https://github.com/inveniosoftware/invenio-github/issues/115
```

## Documentation

I have drafted a temporary doc using a [CodiMD](https://codimd.web.cern.ch/rj7eAr_3R8S92nEevZ63VA). To be moved to a proper documentation format after we finish the epic.

## Specifications

- - Users connect their GitHub accounts via OAuth
- User and organization repositories list fetched to populate GitHub settings page; synchronized every 24h or on demand
- Webhooks created on repository enabling
- On a new (pre)release publish:
  - Event payload received on Zenodo
  - Metadata fetched for the release
    - From basic information (release title, version tag, authors, links)
    - From metadata files like `.zenodo.json` and `CITATION.cff`
  - ZIP ball file of the release downloaded
  - New version record is published with metadata and ZIP ball file
- Release history tracked in GitHub settings for each repository
- Release errors retried and tracked
- Still possible to create "manual" versions, or have drafts in progress that don't interrupt the workflow
- GitHub DOI badge always pointing to the latest DOI/version
- GitHub Settings UI pages (repositories list and repository releases) contain some interactive elements currently implemented with jQuery
  - Toggle button for enabling/disabling integration for repositories
  - "Sync now..." button, triggering repositories fetch from the GitHub API

### Prerequisites

- All metadata fields have to be part of the record/deposit schema (since they can be included in `.zenodo.json` files)

### Next steps

1. [Webhooks module](https://github.com/inveniosoftware/invenio-webhooks) review and integration + GPL -> MIT
2. [GitHub module](https://github.com/inveniosoftware/invenio-github/) review and integration + GPL -> MIT
  a. Fully working backend and programmatic API
  b. Metadata extraction and mapping (translation of `.zenodo.json`, and updated `CITATION.cff` mapping) to InvenioRDM datamodel
  c. Integrate publishing step with the RDMRecord service
3. Migration (and possible rewrite) of interactive UI parts into React

### Nice to haves:

- Admin  for new admin interface
- REST API to support new admin interface + permissions

### Current

![Image](https://user-images.githubusercontent.com/1814661/175057727-2ed1ad28-adf3-40a7-bc31-2cea96af9d5d.png)

![Image](https://user-images.githubusercontent.com/1814661/175057780-a192f041-adbe-4740-a458-92d34447a237.png)

**CITATION.cff generation**

![Image](https://user-images.githubusercontent.com/1814661/175057910-f007d074-bed2-42c6-9014-1a1294092b1d.png)

**Comment by alejandromumo** [comment]
# Sub-Tasks

- [ ] Update invenio-webhook backend
- [ ] Refactor invenio-github backend 
- [ ] Refactor invenio-github UI

**Comment by alejandromumo** [comment]
Closing this issue since the feature was already migrated to RDM. 

Still is missing docs, but that is being tracked separately as part of the v12 release
