### ISSUE TITLE
feature: extra file formats

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/invenio-app-rdm#2253]
From: https://github.com/zenodo/rdm-project/issues/32

- Extra formats: 
  - REST API in Zenodo storing metadata files on disk.
  - Displayed on landing page
  - REST API docs (current zenodo API specification): https://codimd.web.cern.ch/k2hhtG5cR_qLncq14ouVgA#Extra-formats
  - [Implementation commit](https://github.com/zenodo/zenodo/commit/d19f2bcf4998fa99f166e9128cc2333c7b5134b5)

### Current

https://zenodo.org/record/7781669

![Image](https://user-images.githubusercontent.com/1814661/228551000-e7347a64-c934-482b-b9a0-26862c65ac25.png)

### To implement

- In the context of the Arcadia 2 project, we need to add support for annotation files storage and preview/display
  - RFC for "Media files": https://codimd.web.cern.ch/zEYh4vA_QyiUZqk8j-KWhw#Media-files
  
### Other

- The legacy API must be supported (``/api/deposit/depositions/:id/formats`` and ``/records/:id/formats``).
- ZenodoRDM must store and retrieve WADM in addition to Plazi XML.
- Landing page must render the list of extra formats.
- For now, extra formats is an API only feature without a UI.
- The feature requires that formats are defined, hence if no formats are defined, the feature is not active.

## TODO
- [x] add service to handle extra files
- [x] fix locking of the draft's bucket while new version is required
- [x] don't lock the bucket of aux files - they should be editable without new version
- [x] write resource tests
- [x] UI
- [ ] content negotiation
- [ ] legacy URL
- [ ] migration - new fk to media files
