### ISSUE TITLE
Administration: record deletion

### ISSUE THREAD

**Issue by zzacharo** [inveniosoftware/invenio-app-rdm#2289]
RFC: https://codimd.web.cern.ch/y9vYxSjPQ-ytxTZOzzinhA
Mockups: https://balsamiq.cloud/ssg4nq2/p68p1b0/r640D/b6FE5

This a task to design record deletion as part of the administration in InvenioRDM. That will include capabilities, to delete a record (deactivate), restore a record, schedule a record for purge, and purge a record. Moreover, part of this feature is to design the tombstone management of a record while it is deleted.

## Resources

See mockups https://balsamiq.cloud/ssg4nq2/p68p1b0/r640D/b6FE5
See RFC: https://codimd.web.cern.ch/y9vYxSjPQ-ytxTZOzzinhA

## Actions

- [x] Agree that RFC is finalized and integrated with all current feedback
- [x] Ensure that UI design is agreed upon and interfaces from the mockups are clearly updated in the RFC
- [x] Define the current scope from the RFC, both for the backend and frontend implementation
- [x] Make sure the tasks are clearly stated in issues and tracked by this parent issue
```[tasklist]
### Tasks
- [ ] https://github.com/inveniosoftware/invenio-app-rdm/issues/2323
- [ ] https://github.com/inveniosoftware/invenio-app-rdm/issues/2349
- [ ] https://github.com/inveniosoftware/docs-invenio-rdm/issues/689
```
