### ISSUE TITLE
August release checklist

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-app-rdm#233]
Goals:
- Link generation in API endpoints
- Complete semantic-ui transition
- Complete new API switchover (except for files)

Release tasks:
- [x] release invenio-flask-resources ~~0.3.X line~~ 0.2.2
- [x] release invenio-records-resources 0.4.X line  -- 0.4.2
- [x] release invenio-drafts-resources 0.2.X line -- 0.2.4
- [x] release invenio-rdm-records 0.18.X line -- 0.18.3 (before releasing, I am updating invenio-app-rdm to see if anything is missed)
- [x] release react-invenio-deposit 0.5.X line
- [x] release invenio-app-rdm 0.12.X line -- 0.12.5
- [x] release cookie-cutter-invenio-rdm 0.12.X line
- [x] release invenio-cli 0.16.X line

**Comment by lnielsen** [comment]
Complete semantic-UI transition:
- Customization of search results from a user point of view
- Easier setting up of new search pages.

**Comment by fenekku** [comment]
Released!
