### ISSUE TITLE
Search improvements

### ISSUE THREAD

**Issue by ntarocco** [inveniosoftware/invenio-app-rdm#2745]
We need to improve the search results in InvenioRDM. Currently, the search mappings are very basic and tuned to take into account different search queries that users might input.

See also https://github.com/inveniosoftware/invenio-vocabularies/issues/335
See CERN Search mappings tuning: https://gitlab.cern.ch/webservices/cern-search/cern-search-rest-api

~~A related [issue](https://github.com/CERNDocumentServer/cds-rdm/issues/114) already exists, with a [PR](https://github.com/inveniosoftware/invenio-users-resources/pull/127) partially addressing this problem.~~

### Scope
Improve searches of:
- records
- communities
- users
- groups
- vocabularies (affiliations, grants, subjects, names, licenses....)

### Typical search queries
- input of accents, apostrophes, other unicode characters
- partial input: searching for `Mar`, should already propose results for `Mario` without typing the entire name

### Known issues
- Users are findable only when the exact name or e-mail is inserted
- Searching for [Lopez Group](https://inveniordm.web.cern.ch/search?q=Lopez%20Group) does not show the [exact record](https://inveniordm.web.cern.ch/records/t7nrk-4ew71).

### Open questions
- What do we do with titles with LaTeX inside? Do we completely remove the LaTeX formula and it is not searchable?

```[tasklist]
### Tasks
- [ ] https://github.com/inveniosoftware/invenio-app-rdm/issues/2746
- [ ] https://github.com/inveniosoftware/invenio-app-rdm/issues/2747
- [ ] https://github.com/inveniosoftware/invenio-app-rdm/issues/2752
- [ ] https://github.com/inveniosoftware/invenio-app-rdm/issues/2756
- [ ] https://github.com/inveniosoftware/invenio-app-rdm/issues/2759
- [ ] https://github.com/inveniosoftware/invenio-app-rdm/issues/2761
- [ ] https://github.com/inveniosoftware/invenio-app-rdm/issues/1849
- [ ] https://github.com/inveniosoftware/invenio-app-rdm/issues/2766
```

### Search issues not related to search results

```[tasklist]
### Tasks
- [ ] https://github.com/inveniosoftware/invenio-app-rdm/issues/2247
- [ ] https://github.com/inveniosoftware/invenio-app-rdm/issues/2051
- [ ] https://github.com/zenodo/rdm-project/issues/618
```
