### ISSUE TITLE
September Release Checklist

### ISSUE THREAD

**Issue by fenekku** [inveniosoftware/invenio-app-rdm#286]
Release checklist for October 8th-9th workshop

## Features
- [x] As a depositor, I want to go to the deposit page, fill out the fields, publish and be redirected to the record landing page.
- [x] As a depositor, I want to go to the deposit page, fill out the fields, save and be redirected to the record edit page.
- [x] As a depositor, I want to go to the edit page, publish and be redirected to the record landing page. (~~this one is not possible right now. Do we keep?~~ Is possible now in september release)
- [x] As a user I want to go to the search page and search for records
- [ ] As a user I want to go to the search page and sort records by best match and newest
- [x] As a user I want to go to the search page and facet search results

## Releases
- [x] flask-resources 0.3.2 
- [x] marshmallow-utils v0.2.1
- [x] invenio-records-resources v0.6.6
- [x] invenio-drafts-resources v0.4.2
- [x] invenio-rdm-records v0.20.6
- [x] invenio-app-rdm v0.14.3
- [x] cookiecutter-rdm v0.13.0
- [x] invenio-cli v0.17.1

**Comment by ppanero** [comment]
> As a depositor, I want to go to the deposit page, fill out the fields, save and be redirected to the record edit page.

Would require enabling the `save` button and adding the record edit page (e.g. query a record on the drafts endpoint and prefill the deposit form with its content).

Do we have time for this one?

**Comment by ppanero** [comment]
`rdm-records` was unchecked due to mappings (and potentially sorting) PR pending merge (and release)

**Comment by ppanero** [comment]
`app-rdm` was unchecked due to sorting option PR pending merge and release (+ bump `rdm-records` after mappings release)

**Comment by ppanero** [comment]
`rdm records` needs merge and release of https://github.com/inveniosoftware/invenio-rdm-records/pull/184

**Comment by fenekku** [comment]
Closing since September release is out. The only use case I couldn't reproduce is the sort by one. I made an issue for it: https://github.com/inveniosoftware/invenio-app-rdm/issues/309
