### ISSUE TITLE
i18n: fix plurals

### ISSUE THREAD

**Issue by carlinmack** [inveniosoftware/invenio-app-rdm#2905]
Package version (if known): All

## Describe the bug
> A clear and concise description of what the bug is.

Across Invenio we have many places where we have a "count noun" form where we want the noun to respect the count. For example, "1 result" and "2 results". 

**Tasks**

- [ ] Fix translation with count in Python
- [ ] Fix translation with count in Javascript
- [ ] Find all instances where this should be fixed across the modules
- [ ] Fix all instances
- [ ] Correct the [documentation](https://inveniordm.docs.cern.ch/develop/howtos/i18n/#singular-plural)

### Related

https://github.com/inveniosoftware/invenio-app-rdm/issues/2162

**Comment by carlinmack** [comment]
Created issue from leftover task in https://github.com/inveniosoftware/invenio-app-rdm/pull/2895

**Comment by carlinmack** [comment]
I assume that it the solution would also get rid of this avalanche in the console when developing locally 
![image](https://github.com/user-attachments/assets/a8ab8497-7dab-4bf4-9d71-94d54e1330b8)
