### ISSUE TITLE
FAIR score maximization

### ISSUE THREAD

**Issue by carlinmack** [inveniosoftware/invenio-app-rdm#2942]
- [x] List of issues 
- [x] List of scores per tool
- [ ] Triaging
- [ ] Fixes of issues

```[tasklist]
### Tasks
- [ ] F1: Persistence of identifier
- [ ] F2A: Structured metadata                                                                        
- [ ] F3: Metadata identifier in metadata                                                             
- [ ] F4: Searchable                                                                                  
- [ ] A1.1 Uses an open free protocol for data retrieval, Data authentication and authoriazatio       
- [ ] A2: Metadata persistence                                                                        
- [ ] FsF-I2-01M - Metadata uses semantic resources                                                   
- [ ] I1: Machine readable format                                                                     
- [ ] I2: Metadata users FAIR vocabularies                                                            
- [ ] FsF-R1-01MD - Metadata specifies the content of the data.                                       
- [ ] R1.1 Metadata includes license                                                                  
- [ ] FsF-R1.2-01M - Metadata includes provenance information about data creation or generation.      
- [ ] FsF-R1.3-02D - Data is available in a file format recommended by the target research community. 
```

---
Using:
- https://doi.org/10.5281/zenodo.3723281

| Issue                                                                                           | [F-UJI](https://www.f-uji.net/?action=test) | [FAIR Checker](https://fair-checker.france-bioinformatique.fr/check) | [FAIR Evaluator](https://fairsharing.github.io/FAIR-Evaluator-FrontEnd/#!/collections/new/evaluate) | [FAIR Enough](https://fair-enough.semanticscience.org) | [OpenAIRE Validator](https://catalogue.openaire.eu/service/openaire.metadata_validator/overview) |
| ----------------------------------------------------------------------------------------------- | ------------------------------------------- | -------------------------------------------------------------------- | --------------------------------------------------------------------------------------------------- | ------------------------------------------------------ | ------------------------------------------------------------------------------------------------ |
| Score                                                                                           | 79%                                         | 92%                                                                  | 64%                                                                                                 | 72%                                                    | 80%                                                                                              |
| F1: Persistence of identifier                                                                   |                                             |                                                                      | ❌                                                                                                   | ❌                                                      |                                                                                                  |
| F2A: Structured metadata                                                                        |                                             | ❌                                                                    |                                                                                                     |                                                        |                                                                                                  |
| F3: Metadata identifier in metadata                                                             |                                             |                                                                      | ❌                                                                                                   | ❌                                                      |                                                                                                  |
| F4: Searchable                                                                                  |                                             |                                                                      | ⏺️ (no fix needed)                                                                                                 | ⏺️ (no fix needed)                                                     |                                                                                                  |
| A1.1 Uses an open free protocol for data retrieval, Data authentication and authoriazatio       |                                             |                                                                      |                                                                                                     | ❌                                                      |                                                                                                  |
| A2: Metadata persistence                                                                        |                                             |                                                                      | ❌                                                                                                   | ❌                                                      |                                                                                                  |
| FsF-I2-01M - Metadata uses semantic resources                                                   | ❌                                           |                                                                      |                                                                                                     |                                                        |                                                                                                  |
| I1: Machine readable format                                                                     |                                             | ❌                                                                    | ❌                                                                                                   | ❌                                                      |                                                                                                  |
| I2: Metadata users FAIR vocabularies                                                            |                                             |                                                                      | ❌                                                                                                   | ❌                                                      |                                                                                                  |
| FsF-R1-01MD - Metadata specifies the content of the data.                                       | ❌                                           |                                                                      |                                                                                                     |                                                        |                                                                                                  |
| R1.1 Metadata includes license                                                                  |                                             |                                                                      | ❌                                                                                                   | ❌                                                      |                                                                                                  |
| FsF-R1.2-01M - Metadata includes provenance information about data creation or generation.      | ❌                                           |                                                                      |                                                                                                     |                                                        |                                                                                                  |
| FsF-R1.3-02D - Data is available in a file format recommended by the target research community. | ❌                                           |                                                                      |                                                                                                     |                                                        |                                                                                                  |
Notes:

* [F-UJI](https://www.f-uji.net/?action=test)
	* Score: 79%
	* FAIR level: advanced (highest)
	* Test: FsF Metrics v0.5
	* F: 7/7 advanced
	* A : 3/3 advanced
	* I: 3/4 moderate
		* FsF-I2-01M-2	Namespaces of known semantic resources can be identified in metadata
			* NO known vocabulary namespace URI is found which is listed in the LOD registry
				* Check if known namespace(s) are used in structured metadata (RDF, XML) which exist(s) in a LOD registry -: ['http://www.openarchives.org/OAI/2.0/oai_dc.xsd', 'https://github.com/diwis', 'https://zenodo.org/api/records/7559361/files/articles_by_influence.csv', 'https://zenodo.org/records', 'https://pages.semanticscholar.org', 'https://zenodo.org/api/records/7559361/files/articles_by_influence_alt.csv', 'http://schema.datacite.org/oai/oai-1.1/oai.xsd', 'https://zenodo.org/record', 'https://zenodo.org/api/records/7559361/files/articles_by_popularity_alt.csv', 'http://schema.datacite.org/meta/kernel-4/metadata.xsd', 'https://creativecommons.org/licenses/by/4.0', 'https://doi.org/10.5281', 'https://zenodo.org/api/records/7559361/files/articles_by_tweets.csv', 'http://datacite.org/schema', 'https://zenodo.org/communities', 'http://schema.datacite.org/meta/kernel-4.3/metadata.xsd', 'http://datacite.org/schema', 'https://orcid.org', 'https://zenodo.org/api/records/7559361/files/articles_by_popularity.csv', 'https://www.loc.gov/standards/marcxml/schema/MARC21slim.xsd']
	* R: 6/10 moderate
		* FsF-R1-01MD-2	Verifiable data descriptors (file info, measured variables or observation types) are specified in metadata, FsF-R1-01MD-3	Data content matches file type and size or protocol specified in metadata, FsF-R1-01MD-4	Data content matches measured variables or observation types specified in metadata
	        * WARNING	NO info about file size available in given metadata for -: https://zenodo.org/api/records/7559361/files/articles_by_tweets.csv/content
	        * INFO	NO info about data service endpoint available in given metadata for -: https://zenodo.org/api/records/7559361/files/articles_by_tweets.csv/content
	        * WARNING	Could not verify content type from downloaded file -: (expected: text/csv, found: via tika ['text/tsv'] or via header text/plain)
	        * WARNING	NO measured variables found in metadata, skip 'measured_variable' test.
	        * INFO	NO info about data service endpoint available in given metadata for -: https://zenodo.org/api/records/7559361/files/articles_by_tweets.csv/content
	        * WARNING	NO info about file size available in given metadata for -: https://zenodo.org/api/records/7559361/files/articles_by_influence_alt.csv/content
	        * INFO	NO info about data service endpoint available in given metadata for -: https://zenodo.org/api/records/7559361/files/articles_by_influence_alt.csv/content
	        * WARNING	Could not verify content type from downloaded file -: (expected: text/csv, found: via tika ['text/tsv'] or via header text/plain)
	        * WARNING	NO measured variables found in metadata, skip 'measured_variable' test.
	        * INFO	NO info about data service endpoint available in given metadata for -: https://zenodo.org/api/records/7559361/files/articles_by_influence_alt.csv/content
	        * WARNING	NO info about file size available in given metadata for -: https://zenodo.org/api/records/7559361/files/articles_by_popularity_alt.csv/content
	        * INFO	NO info about data service endpoint available in given metadata for -: https://zenodo.org/api/records/7559361/files/articles_by_popularity_alt.csv/content
	        * WARNING	Could not verify content type from downloaded file -: (expected: text/csv, found: via tika ['text/tsv'] or via header text/plain)
	        * WARNING	NO measured variables found in metadata, skip 'measured_variable' test.
	        * INFO	NO info about data service endpoint available in given metadata for -: https://zenodo.org/api/records/7559361/files/articles_by_popularity_alt.csv/content
	        * WARNING	NO info about file size available in given metadata for -: https://zenodo.org/api/records/7559361/files/articles_by_popularity.csv/content
	        * INFO	NO info about data service endpoint available in given metadata for -: https://zenodo.org/api/records/7559361/files/articles_by_popularity.csv/content
	        * WARNING	Could not verify content type from downloaded file -: (expected: text/csv, found: via tika ['text/tsv'] or via header text/plain)
	        * WARNING	NO measured variables found in metadata, skip 'measured_variable' test.
	        * INFO	NO info about data service endpoint available in given metadata for -: https://zenodo.org/api/records/7559361/files/articles_by_popularity.csv/content
	        * WARNING	NO info about file size available in given metadata for -: https://zenodo.org/api/records/7559361/files/articles_by_influence.csv/content
	        * INFO	NO info about data service endpoint available in given metadata for -: https://zenodo.org/api/records/7559361/files/articles_by_influence.csv/content
	        * WARNING	Could not verify content type from downloaded file -: (expected: text/csv, found: via tika ['text/tsv'] or via header text/plain)
	        * WARNING	NO measured variables found in metadata, skip 'measured_variable' test.
	        * INFO	NO info about data service endpoint available in given metadata for -: https://zenodo.org/api/records/7559361/files/articles_by_influence.csv/content
		* FsF-R1.2-01M-2	Metadata contains provenance information using formal provenance ontologies (PROV-O)
			* WARNING	Formal provenance metadata is unavailable
		* FsF-R1.3-02D-1	The format of a data file given in the metadata is listed in the long term file formats, open file formats or scientific file formats controlled list.   c	The format of the data file is a scientific format
			* WARNING	Could not perform file format checks as data content identifier(s) unavailable/inaccesible
* [FAIR Checker](https://fair-checker.france-bioinformatique.fr/check)
	* Score: 91.67%
	* F: 87.5%
		*  F2A: Structured metadata 
			* You should provide discoverability oriented metadata with one of the following properties: dct:title dct:description dcat:accessURL dcat:downloadURL dcat:endpointDescription dcat:endpointURL 
	* A: 100%
	* I: 83.3%
		* I1: Machine readable format
			* You should provide discoverability oriented metadata with one of the following properties: dct:title dct:description dcat:accessURL dcat:downloadURL dcat:endpointDescription dcat:endpointURL 
	* R: 100%
* [FAIR Evaluator](https://fairsharing.github.io/FAIR-Evaluator-FrontEnd/#!/collections/new/evaluate)
	* Evaluation: https://fairsharing.github.io/FAIR-Evaluator-FrontEnd/#!/evaluations/17230
	* Score: 14/22 64%
	* F
		* Data Identifier Persistence - FAILURE: The GUID does not conform with any known permanent-URL system.
		* FAILURE: While (apparent) metadata record identifiers were found (["www.biorxiv.org/content/10.1101/2020.04.11.037093v2", "www.biorxiv.org/content/10.1101/2020.04.11.037093v2"]) none of them matched the initial GUID provided to the test (https://doi.org/10.5281/zenodo.3723281). Exact identifier match is required.
		* FAILURE: Was unable to discover the metadata record by search in Bing using any method
			* I feel like this isn't going to work as we use concept ID to test
	* A:
		* Metric to test if the metadata contains a persistence policy, explicitly identified by a persistencePolicy key (in hashed data) or a http://www.w3.org/2000/10/swap/pim/doc#persistencePolicy predicate in Linked Data.
	* I:
		* FAILURE: The url https://zenodo.org/api/records/7559361/files/articles_by_influence.csv/content failed to resolve via a HEAD call with headers {"Accept"=>"text/turtle, application/ld+json, application/rdf+xml, text/xhtml+xml, application/n3, application/rdf+n3, application/turtle, application/x-turtle, text/n3, text/turtle, text/rdf+n3, text/rdf+turtle, application/n-triples"}, therefore we cannot continue FAILURE: the data could not be found, or does not appear to be in a recognized knowledge representation language.
		* FAILURE: 0 of a total of 33 predicates discovered in the metadata resolved to Linked Data data. The minimum to pass this test is 2/3 (with a minimum of 3 predicates in total).
	* R:
		* FAILURE: No License property was found in the metadata.
* [FAIR Enough](https://fair-enough.semanticscience.org/evaluations?uri=https://doi.org/10.5281/zenodo.3723281)
	* [fair-enough-metadata](https://fair-enough.semanticscience.org/evaluations/fed6debbe1e64213493653846fda668acbd33430), [fair-evaluator-maturity-indicators](https://fair-enough.semanticscience.org/evaluations/618cf892212b94c7371794b3112b22424963ec89), [fair-enough-data](https://fair-enough.semanticscience.org/evaluations/b6a21373a8bef9ed1e10bd25097ff8cb896aff28)
	* Score: 87.5%, 63.6%, 63.6%
	* F:
		* WARN: Unable to resolve https://doi.org/10.5281/zenodo.3723281 using HTTP Accept header {"Accept"=>"text/xhtml,text/xml"}. FAILURE: The GUID does not conform with any known permanent-URL system.
		* FAILURE: [2024-12-12T13:14:21] Could not find links to the metadata identifier None in the RDF metadata
		* WARN: HTTP error 406 Not Acceptable encountered when trying to resolve https://doi.org/10.5281/zenodo.3723281. WARN: Unable to resolve https://doi.org/10.5281/zenodo.3723281 using HTTP Accept header {"Accept"=>"text/xhtml,text/xml"}. FAILURE: While (apparent) metadata record identifiers were found (["www.biorxiv.org/content/10.1101/2020.04.11.037093v2", "www.biorxiv.org/content/10.1101/2020.04.11.037093v2"]) none of them matched the initial GUID provided to the test (https://doi.org/10.5281/zenodo.3723281).  Exact identifier match is required.
		* FAILURE: Was unable to discover the metadata record by search in Bing using any method
	* A: 
		* FAILURE: [2024-12-12T13:14:20] Could not find a persistence policy in the metadata. Searched for the following predicates: ['http://www.w3.org/2000/10/swap/pim/doc#persistencePolicy']
		* FAILURE: [2024-12-12T13:31:45] Could not find the data URI in the subject metadata.
		* FAILURE: [2024-12-12T13:31:45] Could not find the data URI in the subject metadata. WARN: [2024-12-12T13:31:45] Could not find dcterms:accessRights information in metadata. Make sure your metadata contains informations about access rights using one of those predicates: http://purl.org/dc/terms/accessRights
	* I:
		* WARN: Unable to resolve https://doi.org/10.5281/zenodo.3723281 using HTTP Accept header {"Accept"=>"text/xhtml,text/xml"}. FAILURE: The url https://zenodo.org/api/records/7559361/files/articles_by_influence.csv/content failed to resolve via a HEAD call with headers {"Accept"=>"text/turtle, application/ld+json, application/rdf+xml, text/xhtml+xml, application/n3, application/rdf+n3, application/turtle, application/x-turtle, text/n3, text/turtle, text/rdf+n3, text/rdf+turtle, application/n-triples"}, therefore we cannot continue. FAILURE: the data could not be found, or does not appear to be in a recognized knowledge representation language.
		* WARN: Unable to resolve https://doi.org/10.5281/zenodo.3723281 using HTTP Accept header {"Accept"=>"text/xhtml,text/xml"}. WARN:  predicate http://schema.org/affiliation was not found as the SUBJECT of a triple, indicating that it did not resolve to its definition. WARN:  predicate http://ogp.me/ns#description did not resolve to linked data. WARN:  predicate http://ogp.me/ns#description was not found as the SUBJECT of a triple, indicating that it did not resolve to its definition. FAILURE: 0 of a total of 33 predicates discovered in the metadata resolved to Linked Data data.  The minimum to pass this test is 2/3 (with a minimum of 3 predicates in total).
	* R:
		* WARN: Unable to resolve https://doi.org/10.5281/zenodo.3723281 using HTTP Accept header {"Accept"=>"text/xhtml,text/xml"}. WARN: did not find a schema:license predicate that followed the Schema.org license range structure. FAILURE: No License property was found in the metadata.
* [OpenAIRE Validator](https://catalogue.openaire.eu/service/openaire.metadata_validator/overview)
	* Score for content: 88%
	* Score for usage: 72%

**Comment by borsna** [comment]
Including information about the access restrictions in DataCite (already done in Dublin Core) would be great for harvesters that want to know if the resource in open / restricted.
See:
https://guidelines.openaire.eu/en/latest/data/field_rights.html#example

Invenio already does this for dublin core:
https://doi.org/10.5281/zenodo.14191104

```xml
<oai_dc:dc xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:oai_dc="http://www.openarchives.org/OAI/2.0/oai_dc/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/oai_dc/ http://www.openarchives.org/OAI/2.0/oai_dc.xsd">
  ...
  <dc:rights>info:eu-repo/semantics/openAccess</dc:rights>
  <dc:rights>Creative Commons Attribution 4.0 International</dc:rights>
  <dc:rights>https://creativecommons.org/licenses/by/4.0/legalcode</dc:rights>
  ...
</oai_dc:dc>
```
This should be done in DataCite XML as well:

```xml
<resource xmlns="http://datacite.org/schema/kernel-4" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://datacite.org/schema/kernel-4 http://schema.datacite.org/meta/kernel-4.3/metadata.xsd">
  ...
  <rightsList>
    <rights rightsURI="info:eu-repo/semantics/openAccess" />
    <rights rightsURI="https://creativecommons.org/licenses/by/4.0/legalcode" rightsIdentifierScheme="spdx" rightsIdentifier="cc-by-4.0">Creative Commons Attribution 4.0 International</rights>
  </rightsList>
  ...
</resource>
