### ISSUE TITLE
customisation: customising react UI

### ISSUE THREAD

**Issue by zzacharo** [inveniosoftware/invenio-app-rdm#78]
We need to integrate react in some of `invenio-app-rdm` UI templates. More specifically, the search page should be a react application that uses https://github.com/inveniosoftware/react-searchkit. In this fashion we need to provide some customisation in the level of:
* React templates (e.g search results)
* Jinja search templates (e.g customised search header template)

The solution to achieve the above involves the following PRs:
* [x] inveniosoftware/invenio-assets#105 . Webpack config `@templates` alias to dynamically import react templates from an instance.
* [x] inveniosoftware/react-searchkit#91 . External search triggering through a new introduced event listener. With this we can split the search page in a `jinja` template that can render to react applications:
    * SearchBar application which renders a search bar and is able to trigger a search through the event listener
    * Results page where the results are displayed along with facets, pagination, sorting, etc.
    * With this splitting the users of `invenio-app-rdm` can configure easily their search header 
       layout and still having an out of the box search interface. SearchBar can be included in their 
       custom template by just using a macro function.
* [x] inveniosoftware/cookiecutter-invenio-rdm#42. Introducing 2 theme folders that users can 
   override css for the main and search page accordingly.
* [x] inveniosoftware/invenio-app-rdm#62. This introduces:
    * New search UI module with the 2 before-mentioned react applications (SearchBar, Results)
    * Adding react templating support for overriding the react presentational components.
    * Adding overridable `jinja` templates for the search page.

**Comment by ppanero** [comment]
All has been merged and released.
